#version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: LFT-Finder
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RLReplays
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  web:
    build: .
    ports:
      - "5003:5000"  # Geänderter externer Port auf 5003

volumes:
  pgdata:
   